### ISSUE TITLE
請問log_change 的欄位定義?

### ISSUE THREAD

**Issue by JonathanHuangC** [ChickenBenny/Deep-Learing-in-Finance#2]
請問一下, 
1. log_change的公式是甚麼? 與漲跌幅有落差,
2. VAE的KL計算在哪裡,
謝謝

**Comment by ChickenBenny** [comment]
1. 是財務裡面的二階動差
2. 可以看一下/Models/VAE 的檔案~
整體來說這個repo有些漏洞，可能7月會再發一個使用MHGAN+VAE更完整的repo
